# SPDX-License-Identifier: GPL-2.0
#obj-$(CONFIG_NINA_BATTERY)		+= nina_battery.o
obj-$(CONFIG_NINA)		+= nina.o

obj-y		+= ninasysfs.o
obj-y		+= ninabus.o
obj-y		+= ninaproperties.o
obj-y		+= ninapower.o
obj-y		+= ninaosl.o
obj-y		+= ninascan.o
#obj-y		+= utmutex.o
#obj-y		+= evhandler.o
